# Generated by Django 3.1.7 on 2021-04-05 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='Artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist'),
        ),
    ]
