# Generated by Django 3.1.7 on 2021-04-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20210405_1953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
