# Generated by Django 3.1.7 on 2021-04-05 20:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0003_delete_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('venue', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('Artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist')),
            ],
        ),
    ]
